language: rust

rust:
  - stable
  - nightly

os:
  - linux
  - osx

notifications:
  email:
    on_success: never

sudo: false

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

cache:
    apt: true
    directories:
        - target/debug/deps
        - target/debug/build

branches:
  except:
    - staging.tmp

matrix:
  allow_failures:
    - rust: nightly

  include:
  - rust: nightly-2017-07-25
    install:
    - pip install --user travis-cargo
    - export PATH=$PATH:$HOME/.local/bin

    before_script:
    - cargo install clippy --vers 0.0.145
    - cargo install rustfmt-nightly --vers 0.2.1

    script:
    - cargo clippy -- -D warnings
    - cargo fmt -- --write-mode=diff
    # - RUSTFLAGS="-Z sanitizer=leak" cargo test --verbose --target x86_64-unknown-linux-gnu

    after_success:
    - travis-cargo coverage --no-sudo --verify --merge-into target/kcov
    - bash <(curl -s https://codecov.io/bash) -s target/kcov

