language: rust

rust:
  - stable
  - nightly

os:
  - linux
  - osx

notifications:
  email:
    on_success: never

sudo: false

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

cache:
  apt: true
  directories:
    - kcov
    - target/debug/deps
    - target/debug/build

branches:
  except:
    - staging.tmp

matrix:
  allow_failures:
    - rust: nightly

  include:
  - rust: nightly-2017-07-25
    env:
      - RUSTFLAGS="-C link-dead-code"

    before_script:
    - cargo install clippy --vers 0.0.145
    - cargo install rustfmt-nightly --vers 0.2.1

    script:
    - cargo clippy -- -D warnings
    - cargo fmt -- --write-mode=diff
    - cargo test --verbose
    # - RUSTFLAGS="-Z sanitizer=leak" cargo test --verbose --target x86_64-unknown-linux-gnu

    after_success:
    - ./.travis/coverage.sh
