language: rust

rust:
  - stable
  - nightly

os:
  - linux
  - osx

notifications:
  email:
    on_success: never

sudo: false

cache:
  apt: true
  directories:
    - $HOME/.cargo/bin
    - kcov/usr/local/bin
    - target/debug/deps

branches:
  only:
    - staging
    - trying
    - master

matrix:
  allow_failures:
    - rust: nightly
    - rust: nightly-2017-12-08

  include:
  - rust: "1.26.2"

    before_script:
    - rustup component add rustfmt-preview --toolchain 1.26.2

    script:
    - rustfmt -V
    - cargo fmt -- --write-mode diff
    - cargo test --all

    after_success:
    - ./.travis/coverage.sh

  - rust: nightly-2017-12-08
    env:
      global:
        - RUSTFLAGS="-C link-dead-code"

    addons:
      apt:
        packages:
          - binutils-dev
          - libcurl4-openssl-dev
          - zlib1g-dev
          - libdw-dev
          - libiberty-dev

    before_script:
    - bash -c '[ "$(cargo clippy --version 2>/dev/null)" == "0.0.175" ] || cargo install clippy --vers 0.0.175 --force'

    script:
    - cargo clippy -- -D warnings -Z no-trans
    - rm -rf target/debug/{test_,toml_edit-}*
    # - RUSTFLAGS="-Z sanitizer=leak" cargo test --verbose --target x86_64-unknown-linux-gnu

    after_success:
    - ./.travis/coverage.sh
