language: rust
sudo: false

rust:
  - stable
  - nightly

addons:
  apt:
    packages:
      - kcov

after_success: |
  kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/toml_edit-*[^\.d] &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"

branches:
  only:
    - staging
    - trying
    - master
matrix:
  allow_failures:
    - rust: nightly
  include:
  - rust: nightly-2017-07-25
    before_script:
    - cargo install clippy --vers 0.0.145
    - cargo install rustfmt-nightly --vers 0.2.1
    script:
    - cargo clippy -- -D warnings
    - cargo fmt -- --write-mode=diff
os:
  - linux
  - osx
