language: rust

rust:
  - stable
  - nightly

os:
  - linux
  - osx

notifications:
  email:
    on_success: never

sudo: false

cache:
  apt: true
  directories:
    - $HOME/.cargo/bin
    - target/debug/deps

branches:
  except:
    - staging.tmp

matrix:
  allow_failures:
    - rust: nightly

  include:
  - rust: nightly-2017-07-25
    env:
      - RUSTFLAGS="-C link-dead-code"

    addons:
      apt:
        packages:
          - binutils-dev
          - libcurl4-openssl-dev
          - zlib1g-dev
          - libdw-dev
          - libiberty-dev

    before_script:
    - cargo install clippy --vers 0.0.145 || true
    - cargo install rustfmt-nightly --vers 0.2.1 || true

    script:
    - rm -rf target/debug/{test_,toml_edit-}*
    - cargo test --verbose
    - cargo clippy -- -D warnings
    - cargo fmt -- --write-mode=diff
    # - RUSTFLAGS="-Z sanitizer=leak" cargo test --verbose --target x86_64-unknown-linux-gnu

    after_success:
    - ./.travis/coverage.sh
